# Generated by Django 5.2.7 on 2026-04-23 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificado',
            name='cantidad_total_entrega',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado por Calidad'), ('despachado', 'Despachado al Cliente'), ('rechazado', 'Rechazado')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
