# Generated by Django 5.2.7 on 2026-04-23 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_certificado_aprobado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='causa_baja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='requiere_certificado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipo',
            name='descripcion_larga',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='garantia_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='parametro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ParametroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ref_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_cliente', to='certificados.cliente')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.parametro')),
            ],
            options={
                'unique_together': {('cliente', 'parametro')},
            },
        ),
    ]
