# Generated by Django 6.0.4 on 2026-04-30 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0003_producto_cliente_causa_baja_cliente_fecha_baja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='leido_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='clave_doc_especificaciones',
            field=models.CharField(blank=True, help_text='Clave del documento de especificaciones del cliente.', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='causa_baja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='mantenimiento',
            field=models.TextField(blank=True, help_text='Plan / bitácora resumida de mantenimiento.'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='inspeccion_origen',
            field=models.ForeignKey(blank=True, help_text='Inspección anterior cuando ésta es un re-análisis (caso 2.2.9).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reanalisis', to='certificados.inspeccion'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='clave_factor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='parametro',
            name='desviacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grado de error admisible.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='equipo',
            field=models.ForeignKey(blank=True, help_text='Equipo que analiza este factor. Vacío = parámetro global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='certificados.equipo'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='especificacion_interna',
            field=models.CharField(blank=True, help_text='Especificación interna de la planta.', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado por Calidad'), ('despachado', 'Despachado al Cliente'), ('rechazado', 'Rechazado'), ('superado', 'Superado por re-análisis')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='ref_max',
            field=models.DecimalField(decimal_places=2, help_text='Límite superior de referencia internacional.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='ref_min',
            field=models.DecimalField(decimal_places=2, help_text='Límite inferior de referencia internacional.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ventas', 'Ventas'), ('almacen', 'Almacén'), ('lab', 'Laboratorio'), ('calidad', 'Calidad'), ('consulta', 'Consulta (Aseguramiento / Gerencia / Dirección)'), ('admin', 'Administrador')], max_length=20),
        ),
    ]
