# Generated by Django 6.0.4 on 2026-05-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0004_certificado_fecha_lectura_certificado_leido_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='domicilio_entrega',
        ),
        migrations.AddField(
            model_name='cliente',
            name='calle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio_alcaldia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_interior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('lab', 'Laboratorio'), ('aseguramineto calidad', 'Aseguramiento Calidad'), ('control calidad', 'Control calidad'), ('planta', 'Planta'), ('operaciones', 'Operaciones'), ('admin', 'Administrador')], max_length=30),
        ),
    ]
