# Generated by Django 6.0.4 on 2026-05-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0005_remove_cliente_domicilio_entrega_cliente_calle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='municipio_alcaldia',
            new_name='alcaldia',
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
