# Generated by Django 6.0.4 on 2026-05-05 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0006_rename_municipio_alcaldia_cliente_alcaldia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.producto'),
        ),
    ]
