# Generated by Django 6.0.4 on 2026-05-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0008_lote_cantidad_lote_fecha_lote_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='codigo_lote',
        ),
        migrations.AddField(
            model_name='lote',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='secuencia',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
