# Generated by Django 6.0.4 on 2026-05-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0009_remove_lote_codigo_lote_lote_folio_pedido_folio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
