# Generated by Django 6.0.4 on 2026-05-06 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0010_lote_caducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='inspeccion_origen',
            field=models.ForeignKey(blank=True, help_text='Inspección anterior cuando esta es un re-analisis (caso 2.2.9).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reanalisis', to='certificados.inspeccion'),
        ),
    ]
