# Generated by Django 6.0.4 on 2026-05-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0011_alter_inspeccion_inspeccion_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='clave',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
