# Generated by Django 6.0.4 on 2026-05-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0012_inspeccion_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='folio',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
