# Generated by Django 6.0.4 on 2026-05-07 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0013_certificado_folio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='alcaldia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero_exterior',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero_interior',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='caducidad',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='folio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_entrega_calle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_entrega_ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_entrega_codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_entrega_colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_entrega_estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_entrega_interior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_entrega_misma',
            field=models.BooleanField(default=True, help_text='Usar la misma dirección fiscal para entrega'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_entrega_numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_fiscal_calle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_fiscal_ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_fiscal_codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_fiscal_colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_fiscal_estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_fiscal_interior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_fiscal_numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='codigo_lote',
            field=models.CharField(default='L-TEMP', max_length=50),
        ),
        migrations.AddField(
            model_name='lote',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='fecha_produccion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='folio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='clave',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='inspeccion_origen',
            field=models.ForeignKey(blank=True, help_text='Inspección anterior cuando ésta es un re-análisis (caso 2.2.9).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reanalisis', to='certificados.inspeccion'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='certificados.pedido'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='secuencia',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.CharField(max_length=255),
        ),
    ]
