# Generated by Django 6.0.4 on 2026-05-07 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0014_remove_cliente_alcaldia_remove_cliente_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificados.producto'),
        ),
    ]
