# Generated by Django 6.0.4 on 2026-05-07 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0015_alter_pedido_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificados.equipo'),
        ),
    ]
