# Generated by Django 6.0.4 on 2026-05-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0017_venta_pedido_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_cliente',
            field=models.CharField(blank=True, help_text='ID del cliente en SAP Business ByDesign', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ventas', 'Ventas'), ('lab', 'Laboratorio'), ('aseguramiento calidad', 'Aseguramiento Calidad'), ('control calidad', 'Control Calidad'), ('planta', 'Planta'), ('operaciones', 'Operaciones'), ('gerente planta', 'Gerente de Planta'), ('director operaciones', 'Director de Operaciones'), ('admin', 'Administrador')], max_length=30),
        ),
    ]
