# Generated by Django 6.0.4 on 2026-05-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0018_cliente_id_cliente_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='pedido',
        ),
        migrations.AddField(
            model_name='lote',
            name='pedidos',
            field=models.ManyToManyField(blank=True, related_name='lotes', to='certificados.pedido'),
        ),
    ]
