# Generated by Django 6.0.4 on 2026-05-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0019_lote_pedido_m2m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='pedidos',
            new_name='pedido',
        ),
    ]
