# Generated by Django 6.0.4 on 2026-05-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0020_rename_pedidos_lote_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='direccion_envio_calle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='direccion_envio_ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='direccion_envio_codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='direccion_envio_colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='direccion_envio_estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='direccion_envio_interior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='direccion_envio_numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
